# Generated by Django 3.1.2 on 2021-09-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20210916_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnetmodel',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='foxnewsmodel',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='nytimesmodel',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='pcmagmodel',
            name='source_id',
        ),
        migrations.DeleteModel(
            name='MasterModel',
        ),
    ]
